apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: edunexus.azurecr.io/notification-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: EMAIL_USER
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: EMAIL_PASS
            - name: KAFKA_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: KAFKA_API_KEY
            - name: KAFKA_SECRET
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: KAFKA_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - port: 3003
  selector:
    app: notification-service
