apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: edunexus.azurecr.io/chat-service:latest
          ports:
            - containerPort: 3006
          env:
            - name: CHAT_AND_STREAM_DB
              valueFrom:
                configMapKeyRef:
                  name: chat-service-config
                  key: CHAT_AND_STREAM_DB
            - name: AZURE_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: chat-service-config
                  key: AZURE_DB_URI
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                configMapKeyRef:
                  name: chat-service-config
                  key: JWT_ACCESS_TOKEN_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  ports:
    - port: 3006
  selector:
    app: chat-service
